name: unit-test
run-name: ${{ github.author }} is running unit tests
on: [push]

jobs:
  running-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "Username is ${{ secrets.DOCKERHUB_USERNAME }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-app
      - run: docker-compose up -d --build
      - run: docker-compose ps
      - name: Run unit testing
        run: docker-compose exec -it web bun run test
      - run: docker-compose down
